"""
acoustic/train.py — Task B
===========================
Trains the CoughCNN on synthetic data generated by the preprocessing pipeline.

Usage:
    python acoustic/train.py

Outputs:
    acoustic/saved_model/   — Keras SavedModel format
"""

import os
import sys
import logging

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-8s  %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)

# ── Config ────────────────────────────────────────────────────────────────────
N_SAMPLES    = 400     # total synthetic samples (100 per class)
EPOCHS       = 25
BATCH_SIZE   = 32
VAL_SPLIT    = 0.20
SAVED_DIR    = os.path.join(os.path.dirname(__file__), 'saved_model')


def main():
    try:
        import tensorflow as tf
        from tensorflow.keras.utils import to_categorical
        from tensorflow.keras.callbacks import (
            EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
        )
    except ImportError:
        logger.error("TensorFlow required: pip install tensorflow")
        sys.exit(1)

    from acoustic.preprocess import generate_dummy_dataset, NUM_CLASSES
    from acoustic.model import build_cough_cnn

    logger.info(f"TensorFlow version: {tf.__version__}")
    logger.info(f"GPUs available: {tf.config.list_physical_devices('GPU')}")

    # ── Generate / load data ──────────────────────────────────────────────────
    import numpy as np
    data = np.load("real_cough_data.npz")
    X, y = data['X'], data['y']
    y_cat = to_categorical(y, num_classes=NUM_CLASSES)
    logger.info(f"Dataset: X={X.shape}  y={y_cat.shape}")

    # ── Build model ───────────────────────────────────────────────────────────
    model = build_cough_cnn()
    model.summary(print_fn=logger.info)

    # ── Callbacks ─────────────────────────────────────────────────────────────
    os.makedirs(SAVED_DIR, exist_ok=True)
    callbacks = [
        EarlyStopping(
            monitor='val_accuracy',
            patience=7,
            restore_best_weights=True,
            verbose=1
        ),
        ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=4,
            min_lr=1e-6,
            verbose=1
        ),
        ModelCheckpoint(
            filepath=os.path.join(SAVED_DIR, 'best_model.h5'),
            monitor='val_accuracy',
            save_best_only=True,
            verbose=1
        ),
    ]

    # ── Train ─────────────────────────────────────────────────────────────────
    logger.info("Starting training …")
    history = model.fit(
        X, y_cat,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        validation_split=VAL_SPLIT,
        callbacks=callbacks,
        verbose=1
    )

    # ── Save final model ──────────────────────────────────────────────────────
    final_model_path = os.path.join(SAVED_DIR, 'final_model.keras')
    model.save(final_model_path)
    logger.info(f"✅ Model saved to: {final_model_path}")

    # ── Print summary ─────────────────────────────────────────────────────────
    best_epoch = history.history['val_accuracy'].index(
        max(history.history['val_accuracy'])
    ) + 1
    best_val_acc = max(history.history['val_accuracy'])
    logger.info(f"Best val accuracy: {best_val_acc:.4f} at epoch {best_epoch}")
    logger.info("Run 'python acoustic/export_model.py' to export for the web.")


if __name__ == '__main__':
    main()
